import type { Metadata } from 'next';
import { Lato } from 'next/font/google';
import './globals.css';
import Header from '@/components/ui/header';
import Copyright from '@/components/ui/copyright';

const lato = Lato({
  subsets: ['latin'],
  weight: '400',
});

export const metadata: Metadata = {
  title: 'field Marshal India',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${lato.className} antialiased flex flex-col min-h-screen`}
      >
        <Header />
        {children}
        <Copyright />
      </body>
    </html>
  );
}
